[package]
name = "tags"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
toml.workspace = true
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
lazy_static.workspace = true
