[package]
name = "custom_iters"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = {version ="1.8", optional = true}
irontraits.workspace = true

[features]
default = ["rayon"]