[package]
name = "ironstructs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ranger.workspace = true
custom_iters.workspace = true

[features]
default = ["rayon"]
rayon = [
    "ranger/rayon"
]
